### ISSUE TITLE
Run with a Custom Dataset

### ISSUE THREAD

**Issue by rohitkalla9** [alinajadebarnett/iaiabl#2]
Hello, can you share your data directory structure if others want to run the code with a different dataset?
Thanks,
Rohit

**Comment by alinajadebarnett** [comment]
Yes! The data structure is:

```
train/
   classname1/
        datafile.npy
        nextdatafile.npy
        ...
   classname2/
        datafile2.npy
        nextdatafile2.npy
        ...
   ...
val/
   classname1/
        datafile3.npy
        nextdatafile3.npy
        ...
   classname2/
        datafile4.npy
        nextdatafile4.npy
        ...
   ...
test/
   classname1/
        datafile5.npy
        nextdatafile5.npy
        ...
   classname2/
        datafile6.npy
        nextdatafile6.npy
        ...
   ...
push_optional/
   classname1/
        datafile7.npy
        nextdatafile7.npy
        ...
   classname2/
        datafile8.npy
        nextdatafile8.npy
        ...
   ...
   
```

So you have train, val, test as top level directories. Each of these contain n directories where n is the number of classes. Those directories contain the data files. Class number will be assigned alphabetically such that the class that appears first in alphabetical order is class 0. Optionally, you can have a push directory that is different from the train directory.
